apiVersion: v1
kind: Service
metadata:
  name: admission-service
spec:
  type: NodePort # Use LoadBalancer if on AWS/GCP/Azure
  selector:
    app: admission-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007 # Access app at NodeIP:30007
